### PR TITLE
improve default freeswitch config

### PR DESCRIPTION
**Pull request by freddy36**

### CODE REVIEW

**Comment by freddy36** [comment]
With or without the escaped dots it should result in the same logic.
Network_addr will always have the format X.X.X.X for the standard setup so the escaped ANY regex matches must match the dots in the network_addr.
I would prefer this slightly relaxed IP matching over having to introduce a second variable for the regex version of the IP.

**Comment by mwolff44** [comment]
have you tested it like that ? if it is ok, i merge it

**Comment by freddy36** [comment]
Yes it's working for me like this.

**Comment by mwolff44** [comment]
for me it is ok from security point of view, as it is easy and recommanded to setup a firewall on FS VMs.

**Pull request merged**
